sudo: required
dist: trusty

language: python
python: '2.7'

install:
  - pip install ansible

before_script:
  - echo localhost > deployment/testing
script:
  - ansible-playbook -i deployment/testing "deployment/playbook.yml" --connection=local --sudo --syntax-check
  - ansible-playbook -i deployment/testing "deployment/playbook.yml" --connection=local --sudo
