sudo: required
dist: trusty

addons:
  postgresql: "9.3" 
  apt:
    packages:
    - postgresql-server-dev-9.3

language: python
python: '2.7'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  - pip install ansible

before_script:
  - echo localhost > deployment/testing

script:
  - ansible-playbook -i deployment/testing "deployment/playbook.yml" --connection=local --sudo --syntax-check
  - ansible-playbook -i deployment/testing "deployment/playbook.yml" --connection=local --sudo
