---

### Add postgres repository key
- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present 

### Add postgres repository
- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present
  
### Iterate over and install required packages
- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    
  with_items:
    - python-software-properties
    - cowsay
    - python-setuptools
    - libpq-dev
    - python-psycopg2
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }} 
    - git
    - postgresql-9.3-pgtap
  
- name: Ensure the PostgreSQL service is running
  service: name=ssh state=started
