---

- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present 

- name: Add postgres repository
  #apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main' state=present
  

- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
    
  with_items:
    - python-software-properties
    - cowsay
    - python-setuptools
    - libpq-dev
    - python-psycopg2
    - postgresql-{{ postgresql_version }}-postgis-{{ postgis_version }} 
    - git

#name: Ensure the PostgreSQL service is running
- service: name=ssh state=started

- name: Ensure database is created
  become_user: postgres
  become: yes
  postgresql_db: name={{ pg_db_name }}
                 encoding='UTF-8'
                 state=present
 
#- name: Adds postgis to the database "{{ pg_db_name }}"
  #become_user: postgres
  #become_method: su
  #become: yes

  #postgresql_ext: name=postgis
  #                db={{ pg_db_name }}
  #                state=present
   

- name: make template_postgis a template
  become_user: postgres
  become: yes
  command: psql -d {{ pg_db_name }} -c 'CREATE EXTENSION postgis;'
  
#psql -d {{ pg_db_name }} -c 'GRANT ALL ON geometry_columns TO PUBLIC;'
#psql -d {{ pg_db_name }} -c 'GRANT ALL ON spatial_ref_sys TO PUBLIC;

                
#- name: Ensure schema is created # Released ansible 2.3
#  become_user: postgres
#  become: yes
#  postgresql_schema: name=test_scehma
#                     database=test_db
#                     state=present
 
- name: Ensure user has access to the database
  become_user: postgres
  become: yes
  postgresql_user: db={{ pg_db_name }}
                   name={{ pg_user }}
                   password={{ pg_user_pass }}
                   priv=ALL
                   state=present
                   encrypted=no

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  become: yes
  postgresql_user: name={{ pg_user }}
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
                   state=present

- name: Clone git gaz repo
  git: repo={{ git_repo }}
       dest={{ git_dest }}

- name: install database
  become_user: postgres
  become: yes
  command: psql -f {{ item }}

  with_items:
    - "{{ git_dest }}/src/sql/gazetteer_roles.sql"
    - "{{ git_dest }}/src/sql/gazetteer_schema.sql"



